// Apps panel, time thief, poster export
import { invoke, getTimeRange, showToast, currentTimeRange } from './utils.js';
import { renderCategoryChart, renderAppUsageChart } from './charts.js';

export async function loadAppsPanel() {
  const { start, end } = getTimeRange(currentTimeRange);

  try {
    const breakdown = await invoke('get_category_breakdown', { startMs: start, endMs: end });
    renderCategoryChart(breakdown);
  } catch (e) {
    console.error('Failed to load category breakdown:', e);
  }

  try {
    const usage = await invoke('get_app_usage', { startMs: start, endMs: end });
    renderAppUsageChart(usage);
  } catch (e) {
    console.error('Failed to load app usage:', e);
  }

  try {
    const thief = await invoke('get_time_thief', { startMs: start, endMs: end });
    const section = document.getElementById('timeThiefSection');
    if (thief) {
      section.style.display = 'flex';
      document.getElementById('thiefName').textContent = thief.app_name;
      document.getElementById('thiefIcon').textContent = thief.app_name.charAt(0);
      document.getElementById('thiefHours').textContent = thief.hours_stolen.toFixed(1);
      document.getElementById('thiefSwitches').textContent = thief.switch_count;
      const mins = Math.round(thief.longest_session_ms / 60000);
      document.getElementById('thiefLongest').textContent = mins >= 60 ? `${(mins/60).toFixed(1)}h` : `${mins}m`;
    } else {
      section.style.display = 'none';
    }
  } catch (e) {
    console.error('Failed to load time thief:', e);
  }
}

// Export poster
document.getElementById('exportPosterBtn').addEventListener('click', async () => {
  const poster = document.querySelector('.wanted-poster');
  if (!poster) return;

  const name = poster.querySelector('.wanted-name')?.textContent || 'Unknown';
  const initial = poster.querySelector('.wanted-icon')?.textContent?.trim() || '?';
  const stats = poster.querySelectorAll('.wanted-stat-value');
  const labels = poster.querySelectorAll('.wanted-stat-label');
  const reward = poster.querySelector('.wanted-reward')?.textContent || '';

  const w = 480, h = 640;
  const canvas = document.createElement('canvas');
  canvas.width = w;
  canvas.height = h;
  const ctx = canvas.getContext('2d');

  const grad = ctx.createLinearGradient(0, 0, w, h);
  grad.addColorStop(0, '#3B2F1A');
  grad.addColorStop(1, '#2A1F10');
  ctx.fillStyle = grad;
  ctx.fillRect(0, 0, w, h);

  ctx.strokeStyle = '#8B6914';
  ctx.lineWidth = 6;
  ctx.strokeRect(12, 12, w - 24, h - 24);
  ctx.strokeRect(20, 20, w - 40, h - 40);

  ctx.fillStyle = '#D4A843';
  ctx.font = 'bold 48px "Space Grotesk", sans-serif';
  ctx.textAlign = 'center';
  ctx.shadowColor = '#1A1205';
  ctx.shadowOffsetX = 3;
  ctx.shadowOffsetY = 3;
  ctx.fillText('WANTED', w/2, 80);
  ctx.shadowOffsetX = 0;
  ctx.shadowOffsetY = 0;

  ctx.fillStyle = '#8B6914';
  ctx.font = '14px "Space Grotesk", sans-serif';
  ctx.fillText('T I M E   T H I E F', w/2, 110);

  ctx.beginPath();
  ctx.arc(w/2, 200, 50, 0, Math.PI * 2);
  ctx.strokeStyle = '#8B6914';
  ctx.lineWidth = 3;
  ctx.stroke();
  ctx.fillStyle = 'rgba(212,168,67,0.1)';
  ctx.fill();

  ctx.fillStyle = '#D4A843';
  ctx.font = 'bold 36px "Space Grotesk", sans-serif';
  ctx.fillText(initial, w/2, 214);

  ctx.fillStyle = '#E8D5A3';
  ctx.font = 'bold 28px "Space Grotesk", sans-serif';
  ctx.fillText(name, w/2, 300);

  const statY = 370;
  for (let i = 0; i < Math.min(stats.length, 3); i++) {
    const x = w/4 + (i * w/4);
    ctx.fillStyle = '#D4A843';
    ctx.font = 'bold 24px "Space Grotesk", sans-serif';
    ctx.fillText(stats[i].textContent, x, statY);
    ctx.fillStyle = '#8B6914';
    ctx.font = '10px "Space Grotesk", sans-serif';
    ctx.fillText(labels[i]?.textContent?.toUpperCase() || '', x, statY + 20);
  }

  ctx.strokeStyle = '#5A4510';
  ctx.lineWidth = 1;
  ctx.beginPath();
  ctx.moveTo(60, 420);
  ctx.lineTo(w - 60, 420);
  ctx.stroke();

  ctx.fillStyle = '#8B6914';
  ctx.font = '14px "Space Grotesk", sans-serif';
  ctx.fillText(reward, w/2, 455);

  ctx.fillStyle = 'rgba(139,105,20,0.3)';
  ctx.font = '11px "Space Grotesk", sans-serif';
  ctx.fillText('Generated by ClickGlow', w/2, h - 30);

  const btn = document.getElementById('exportPosterBtn');
  btn.textContent = 'Saving...';
  btn.disabled = true;
  try {
    const dataUrl = canvas.toDataURL('image/png');
    const base64 = dataUrl.split(',')[1];
    const ts = new Date().toISOString().slice(0, 10);
    const path = await invoke('save_png_base64', { base64Data: base64, filename: `clickglow-wanted-${ts}.png` });
    btn.textContent = 'Saved!';
    showToast('Saved to ' + path);
    setTimeout(() => { btn.textContent = 'Export Poster as PNG'; btn.disabled = false; }, 3000);
  } catch (e) {
    console.error('Failed to save poster:', e);
    btn.textContent = 'Export Failed';
    showToast('Export failed: ' + e, true);
    setTimeout(() => { btn.textContent = 'Export Poster as PNG'; btn.disabled = false; }, 3000);
  }
});
